[package]
name = "rsvcs"
version = "1.0.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.41", features = ["derive"] }
flate2 = "1.1.2"
serde = { version = "1.0.219", features = ["derive"] }
sha2 = "0.10.9"
tar = "0.4.44"
toml = "0.9.2"
zstd = "0.13.3"
