[package]
name = "rsvcs"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.41"
clap = { version = "4.5.41", features = ["derive"] }
flate2 = "1.1.2"
sha2 = "0.10.9"
tail = "0.3.0"
tar = "0.4.44"
zstd = "0.13.3"
